source "https://rubygems.org"
gem "webrick"
gem "jekyll", ">= 3.7", "< 5.0"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-sitemap", "~> 1.3"
gem "jekyll-gist", "~> 1.5"
gem "jekyll-feed", "~> 0.1"
gem "jekyll-include-cache", "~> 0.1"
gem "bundler"
gem "rake", ">= 12.3.3"